server:
  port: 8888
spring:
      thymeleaf:
                cache: false
                prefix: classpath:/templates/
                suffix: .html
                encoding: UTF-8
                mode: HTML5