server:
  port: 8888
spring:
      thymeleaf:
                cache: false
                prefix: classpath:/templates/
                suffix: .html
                encoding: UTF-8
                mode: HTML5

prop:
  upload-folder: zutnlp-text/zutnlp-text-web/src/main/resources/static/text/